name: Frontend Deploy

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy-react-web:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: frontend npm install, build
      working-directory: ./frontend
      run: |
        yarn install
        yarn run build --if-present
    - name: swagger npm install, build
      working-directory: ./swagger
      run: |
        yarn install
        yarn run swagger:build --if-present
    - name: move build swagger file
      run: |
        mv ./swagger/swagger/ ./frontend/build/
        touch ./frontend/build/.nojekyll
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: frontend/build
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: frontend/build